package com.maaza.quick.base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import com.maaza.quick.Util;

public class BaseManager {

    private static final String CREATE1 = "create table item (id integer generated by default as identity (start with 1) primary key, name varchar (20), status boolean)";
    private static final String CREATE2 = "create table user (id integer generated by default as identity (start with 1) primary key, name varchar (20), status boolean)";
    private static final String INSERT1 = "insert into item (id, name, status) values (default, ?, ?)";
    private static final String INSERT2 = "insert into user (id, name, status) values (default, ?, ?)";
    private static final String DROP1 = "drop table item";
    private static final String DROP2 = "drop table user";

    public void create() throws SQLException {
        try (Connection con = Util.getCon();
                PreparedStatement ps1 = con.prepareStatement(CREATE1);
                PreparedStatement ps2 = con.prepareStatement(CREATE2)) {
            ps1.executeUpdate();
            ps2.executeUpdate();
        }
    }

    public void insert() throws SQLException {
        try (Connection con = Util.getCon();
                PreparedStatement ps1 = con.prepareStatement(INSERT1);
                PreparedStatement ps2 = con.prepareStatement(INSERT2)) {
            ps1.setString(1, "aaaaa");
            ps1.setBoolean(2, true);
            ps1.executeUpdate();
            ps2.setString(1, "bbbbb");
            ps2.setBoolean(2, true);
            ps2.executeUpdate();
        }
    }

    public void drop() throws SQLException {
        try (Connection con = Util.getCon();
                PreparedStatement ps1 = con.prepareStatement(DROP1);
                PreparedStatement ps2 = con.prepareStatement(DROP2)) {
            ps1.executeUpdate();
            ps2.executeUpdate();
        }
    }
}
